### ISSUE TITLE
Max_torque interface in gripper closing unclear

### ISSUE THREAD

**Issue by LarsJanssenTUe** [tue-robotics/hero_bridge#11]
In https://github.com/tue-robotics/hero_bridge/blob/master/src/gripper_controller/gripper_controller.py#L83 the effort that the gripper exerts is specified to be as follows:

```
        goal = GripperApplyEffortGoal()
        goal.effort = -effort * HAND_MOMENT_ARM_LENGTH
        self._grasp_client.send_goal(goal)
```

Note that HAND_MOVEMENT_ARM_LENGTH is specified as: ``HAND_MOMENT_ARM_LENGTH = 0.07``.
The effort is specified (in the case of closing the gripper) according to:

```
            if goal.command.max_torque > 0:
                return self._close_gripper(goal.command.max_torque)
            else:
                return self._close_gripper()
```
In which the max_torque can be specified in the given command. There are however no bounds given for the max_torque. According to https://docs.hsr.io/hsrb_user_manual_en/overview/basic_specifications.html the maximum force that the gripper can exert is 40N (! so not Nm, but N!). So it is possible that the maximum effort that could theoretically be given is 40, however the effort could also indicate a scaled value between 0-1. This brought me to the messages from tmc, specifically to the GripperApplyEffortAction and GripperApplyEffortGoal messages (tmc_control_msgs). However in this message there is literally no usefull information on what you should input here. All that is known is that the GripperApplyEffortGoal should be a float.......

So the interface is unclear as it can be, I do not know where to look for more info.

**Comment by LarsJanssenTUe** [comment]
@MatthijsBurgh any idea how we could continue with this?

**Comment by MatthijsBurgh** [comment]
@LarsJanssenTUe I think the only way to go is to contact Toyota.

**Comment by LarsJanssenTUe** [comment]
After consulting the HSRB Development Manual and with the help of Peter I found the original Toyota interface for the close gripper command. Our interface is slightly different but has the same implementation, therefore the effort that is given in the close gripper command should be equal to the following:

```
            effort (float): Force applied to grasping [N]
                            'effort' should be positive number

I will check the current documentation and add/clear up what is missing.
